# Generated by Django 5.2.7 on 2025-11-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailystretch_app', '0007_profile'),
        ('dailystretch_app', '0007_userprofile'),
    ]

    operations = [
    ]
