# Generated by Django 5.2.7 on 2025-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystretch_app', '0009_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
